name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 1: O contexto do build agora é a pasta 'app'
    - name: Build Backend Image
      run: docker build app --file app/Dockerfile --tag educafuturo-backend:latest

    # Passo 2: O contexto do build agora é a pasta 'frontend'
    - name: Build Frontend Image
      run: docker build frontend --file frontend/Dockerfile --tag educafuturo-frontend:latest